name: "Continuous Integration"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-versions: ["~1.1.0", "~1.2.0", "latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform - ${{ matrix['terraform-versions'] }}
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix['terraform-versions'] }}

      - name: Terraform Validate
        run: |
          cd demo
          terraform init
          terraform validate
